{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ethercalc.secretName" . }}
  labels:
    {{- include "ethercalc.labels" . | nindent 4 }}
type: Opaque
stringData:
  ETHERCALC_KEY: {{ .Values.secrets.key | default "" | quote }}
  ETHERCALC_MIGRATE_TOKEN: {{ .Values.secrets.migrateToken | default "" | quote }}
{{- end }}
