#!/usr/bin/env bun
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DEFAULT_INPUT = path.join(__dirname, '../node_modules/socialcalc/dist/SocialCalc.js');
const DEFAULT_OUTPUT = path.join(__dirname, '../src/socialcalc.bundled.ts'); // Save as TS so it resolves correctly in vitest

// SocialCalc 2.3.0 from github:audreyt/socialcalc is strict-mode clean and
// already has `factory.call(root, root)` (transform #3 from AGENTS.md §16.A).
// The remaining transforms are the two DOM shim redirects:
//   (1) route document.createElement through our ShimNode namespace
//   (2) silence alert() on error paths
// Plus one wrapper-level rewrite so our host-binding IIFE still captures root:
//   (3) neutralize the UMD's `globalThis` fallback so `root === this === host`
//       and `window === host` inside the factory — otherwise workerd's real
//       async setTimeout leaks in and recalc never unrolls synchronously.
const CREATE_ELEMENT_PATTERN = /document\.createElement\(/g;
const ALERT_PATTERN = /alert\(/g;
const GLOBALTHIS_MARKER = "typeof globalThis !== 'undefined' ? globalThis : this";
// Single source of truth: derive the search regex from the literal marker
// itself (inline escape — GLOBALTHIS_MARKER has no `g` flag semantics on
// its own) so the two can never drift apart.
const GLOBALTHIS_PATTERN = new RegExp(GLOBALTHIS_MARKER.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g');

/** Thrown when a required compatibility pattern is missing, drifted, or ambiguous. */
export class TransformError extends Error {
  constructor(message) {
    super(message);
    this.name = 'TransformError';
  }
}

/**
 * Counts non-overlapping matches of `pattern` (must carry the `g` flag) in
 * `src` and throws a precise `TransformError` unless the count satisfies
 * `exact` (a specific required count) or `min` (a floor, default 1 i.e.
 * "must be nonzero"). Regenerating from a drifted/renamed upstream source
 * must fail loudly here rather than silently emit an unpatched bundle.
 */
function assertMatchCount(src, pattern, label, { exact, min = 1 } = {}) {
  const count = (src.match(pattern) ?? []).length;
  if (exact !== undefined ? count !== exact : count < min) {
    const requirement = exact !== undefined ? `exactly ${exact}` : `at least ${min}`;
    throw new TransformError(
      `socialcalc-headless build: "${label}" pattern matched ${count} time(s), expected ${requirement}. ` +
        'Upstream SocialCalc source likely drifted — inspect before regenerating socialcalc.bundled.ts.',
    );
  }
  return count;
}

/**
 * Pure transform: applies the three compatibility rewrites to a raw
 * SocialCalc UMD source string and returns the patched string.
 *
 * Every rewrite is guarded by a match-count assertion first — a silent
 * zero-match rewrite (e.g. upstream renames the globalThis fallback) would
 * otherwise ship a bundle that looks generated but is missing the fix, and
 * for the globalThis rewrite specifically that means recalc silently stops
 * unrolling synchronously in the DO (real async setTimeout leaks back in).
 * `document.createElement(`/`alert(` only need to be nonzero (their exact
 * counts vary release to release); the globalThis fallback string is a
 * single UMD wrapper site, so it must match exactly once — more than one
 * match means a single unqualified `String.replace` can no longer safely
 * target "the" wrapper occurrence.
 */
export function transformSocialCalcSource(src) {
  assertMatchCount(src, CREATE_ELEMENT_PATTERN, 'document.createElement(', { min: 1 });
  assertMatchCount(src, ALERT_PATTERN, 'alert(', { min: 1 });
  assertMatchCount(src, GLOBALTHIS_PATTERN, 'globalThis fallback', { exact: 1 });

  let out = src.replace(CREATE_ELEMENT_PATTERN, 'SocialCalc.document.createElement(');
  out = out.replace(ALERT_PATTERN, '(function(){})(');
  out = out.replace(GLOBALTHIS_MARKER, 'this');
  return out;
}

/** Wraps a transformed SocialCalc source string in the host-binding module. */
export function wrapSocialCalcSource(patchedSrc) {
  return `// @ts-nocheck
// Generated by scripts/build.js from audreyt/socialcalc. Do not hand-edit.
import { ShimNode } from './dom-shim';

export function createSocialCalcFactory() {
  const host = {
    setTimeout: function(cb) { cb(); return 0; },
    clearTimeout: function() {}
  };

  let SocialCalc;

  (function() {
    var navigator = { language: "", userAgent: "" };
    // Force the UMD's Node branch so nothing lands on the real
    // globalThis.SocialCalc. define stays undefined so AMD is also skipped.
    var module = { exports: {} };
    var define = undefined;

    ${patchedSrc}

    SocialCalc = module.exports;
  }).call(host);

  SocialCalc.document = SocialCalc.document || {};
  SocialCalc.document.createElement = function (tag) { return new ShimNode(tag); };

  return SocialCalc;
}
`;
}

/**
 * Reads `input` (defaults to the installed `socialcalc` package), applies
 * the compatibility transforms, and writes the wrapped module to `output`
 * (defaults to `src/socialcalc.bundled.ts`). Both paths are overridable so
 * callers (tests, disposable-candidate smokes) can target a temp file
 * without touching the tracked generated bundle.
 */
export function generateBundle({ input = DEFAULT_INPUT, output = DEFAULT_OUTPUT } = {}) {
  const src = fs.readFileSync(input, 'utf8');
  const wrapped = wrapSocialCalcSource(transformSocialCalcSource(src));
  fs.writeFileSync(output, wrapped);
  return { input, output, bytes: Buffer.byteLength(wrapped) };
}

if (import.meta.main) {
  try {
    const result = generateBundle();
    console.log(`Generated ${path.relative(process.cwd(), result.output)}`);
  } catch (err) {
    console.error(`[build] FAIL: ${err instanceof Error ? err.message : String(err)}`);
    process.exitCode = 1;
  }
}
