import type { HttpScenario } from '@ethercalc/shared/oracle-scenarios';

import {
  MINIMAL_SCSAVE,
  ORACLE_PHASE3_TEMPLATE_ROOM,
  requestBodyBase64,
} from './fixtures.ts';

/**
 * Templating / room-autogen scenarios.
 *
 *   GET  /_from/:template   302 → a freshly-cloned room id
 *   GET  /=_new             302 → a new multi-sheet room id
 *   POST /_                 201   create a room with an autogenerated id
 *
 * All three embed a non-deterministic room id in their `Location`
 * (and the POST body), so each gets a `re:` header normalizer in
 * `normalize.ts`. `/_from/:template` requires the template room to
 * exist, so this group MUST run after `room-crud/put-template-room`
 * and before the teardown DELETE removes it. `/=_new` is stateless;
 * `POST /_` creates a room, so the group runs after the empty
 * room-index probes.
 */

const SCSAVE_HEADERS = {
  'Content-Type': 'text/x-socialcalc; charset=utf-8',
} as const;

/**
 * `GET /_from/:template` clones the seeded template room's snapshot into
 * a new room and 302s to `/<new-id>` (no `/edit` because the recording
 * oracle runs without a KEY). The new id is a 12-char base36 string —
 * matched with a regex; the redirect body is ignored. Leaves a clone
 * room in Redis (handled like the form clone, see normalize.ts).
 */
export const GET_FROM_TEMPLATE: HttpScenario = {
  name: 'templating/get-from-template',
  kind: 'http',
  request: {
    method: 'GET',
    path: `/_from/${ORACLE_PHASE3_TEMPLATE_ROOM}`,
  },
};

/**
 * `GET /=_new` allocates a multi-sheet room id and 302s to `/=<new-id>`
 * (no `/edit` — KEY unset). The Location embeds the random id, so it is
 * relaxed to a regex; the redirect body is ignored. Creates no Redis
 * state (the room is materialized only on first write).
 */
export const GET_MULTI_NEW: HttpScenario = {
  name: 'templating/get-multi-new',
  kind: 'http',
  request: {
    method: 'GET',
    path: '/=_new',
  },
};

/**
 * `POST /_` with a SocialCalc save body autogenerates a room id, stores
 * the snapshot, and replies `201` with `Location: /_/<new-id>` and a
 * plaintext body of `/<new-id>`. Both the Location header and the body
 * embed the random id, so both are relaxed via the normalizer.
 */
export const POST_AUTOGEN_ROOM: HttpScenario = {
  name: 'templating/post-autogen-room',
  kind: 'http',
  request: {
    method: 'POST',
    path: '/_',
    headers: SCSAVE_HEADERS,
    bodyBase64: requestBodyBase64(MINIMAL_SCSAVE),
  },
};

export const TEMPLATING_SCENARIOS: readonly HttpScenario[] = [
  GET_FROM_TEMPLATE,
  GET_MULTI_NEW,
  POST_AUTOGEN_ROOM,
];
