/-
  Generated by lsc from xlsx-a1.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «xlsx-a1.types»

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method isValidCol (c : Int) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ c ≥ 0
  do
    return Pure.isValidCol c

method encodeStep (n : Int) return (res : Int)
  require n ≥ 0
  ensures res < n
  ensures res ≥ -1
  do
    return Pure.encodeStep n

method encodeDigit (n : Int) return (res : Int)
  require n ≥ 0
  ensures res ≥ 65
  ensures res ≤ 90
  do
    return Pure.encodeDigit n

method accumCol (col : Int) (charCode : Int) return (res : Int)
  require col ≥ 0
  require charCode ≥ 65
  require charCode ≤ 90
  ensures res ≥ 1
  ensures res ≥ col * 26 + 1
  do
    return Pure.accumCol col charCode

method toZeroBased (col1based : Int) return (res : Int)
  require col1based ≥ 1
  ensures res ≥ 0
  ensures res = col1based - 1
  do
    return Pure.toZeroBased col1based

method roundTripCode (c : Int) (decoded : Int) return (res : Int)
  require c ≥ 0
  require decoded ≥ 1
  ensures res = 0 ∨ res = 1
  ensures decoded = c + 1 → res = 0
  ensures decoded ≠ c + 1 → res = 1
  do
    return Pure.roundTripCode c decoded

method isWithinSocialCalc (c : Int) return (res : Bool)
  ensures res = true ∨ res = false
  ensures res = true ↔ c ≥ 0 ∧ c ≤ 701
  do
    return Pure.isWithinSocialCalc c
