/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import LemmaScript

namespace Pure

def isValidCol (c : Int) : Bool :=
  c ≥ 0

def encodeStep (n : Int) : Int :=
  n / 26 - 1

def encodeDigit (n : Int) : Int :=
  65 + Int.tmod n 26

def accumCol (col : Int) (charCode : Int) : Int :=
  col * 26 + charCode - 64

def toZeroBased (col1based : Int) : Int :=
  col1based - 1

def roundTripCode (c : Int) (decoded : Int) : Int :=
  if decoded = c + 1 then
    0
  else
    1

def isWithinSocialCalc (c : Int) : Bool :=
  c ≥ 0 ∧ c ≤ 701

end Pure
